# Generated by Django 3.1.7 on 2021-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionId', models.IntegerField(verbose_name='职位id')),
                ('positionName', models.CharField(max_length=255, verbose_name='职位名称')),
                ('salary', models.CharField(max_length=255, verbose_name='工资')),
                ('industryField', models.CharField(max_length=255, verbose_name='公司领域')),
                ('companySize', models.CharField(max_length=255, verbose_name='公司规模')),
                ('workYear', models.CharField(max_length=255, verbose_name='工作经验')),
                ('education', models.CharField(max_length=255, verbose_name='学历')),
                ('district', models.CharField(max_length=255, verbose_name='')),
                ('positionDesc', models.TextField(verbose_name='')),
                ('companyDesc', models.TextField(verbose_name='')),
                ('contact', models.CharField(max_length=255, verbose_name='')),
                ('positionUrl', models.CharField(max_length=255, verbose_name='')),
                ('companyType', models.CharField(max_length=255, verbose_name='')),
            ],
        ),
    ]
