# Generated by Django 3.1.7 on 2021-03-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_info',
            name='positionId',
            field=models.IntegerField(unique=True, verbose_name='职位id'),
        ),
    ]
