# Generated by Django 3.2 on 2021-04-10 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20210411_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partjobinfo',
            name='ageMax',
        ),
        migrations.RemoveField(
            model_name='partjobinfo',
            name='ageMin',
        ),
    ]
