# Generated by Django 3.2 on 2021-04-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210411_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job_info',
        ),
    ]
