# Generated by Django 3.2 on 2021-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_delete_job_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '城市', 'verbose_name_plural': '城市'},
        ),
        migrations.AlterModelOptions(
            name='partjobinfo',
            options={'verbose_name': '兼职信息', 'verbose_name_plural': '兼职信息'},
        ),
        migrations.AddField(
            model_name='partjobinfo',
            name='price',
            field=models.CharField(default='', max_length=255, verbose_name='时薪'),
        ),
        migrations.AlterField(
            model_name='partjobinfo',
            name='desc',
            field=models.TextField(verbose_name='描述信息'),
        ),
    ]
