# Generated by Django 3.2 on 2021-04-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210413_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partjobinfo',
            name='price',
            field=models.FloatField(default='', verbose_name='时薪'),
        ),
    ]
